# Generated by Django 3.2.7 on 2021-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0002_auto_20210925_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
