# Generated by Django 3.2.7 on 2021-09-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210925_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
