# Generated by Django 3.2.7 on 2021-09-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag2',
            new_name='Tag',
        ),
    ]
