# Generated by Django 3.2.7 on 2021-09-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_rename_tag2_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='task.project'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='task.event'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
