# Generated by Django 3.2.7 on 2021-09-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210927_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='task.event'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='task.project'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(related_name='activities', to='task.Tag'),
        ),
        migrations.CreateModel(
            name='Project2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('tags', models.ManyToManyField(to='task.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='project2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects2', to='task.project2'),
        ),
    ]
