# Generated by Django 3.2.7 on 2021-09-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_rename_project2_activity_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
