# Generated by Django 3.2.7 on 2021-09-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_delete_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project2',
            new_name='Project',
        ),
    ]
